language: generic
sudo: required
services:
  - docker

before_install:
  - docker build -t dev-main/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true dev-main/docker-react npm run test